### ISSUE TITLE
ID и Array

### ISSUE THREAD

**Issue by sergeyruskov** [Kroid/tick-tack-30line#1]
Учусь гавнокодить, наткнулся на Вашу игрушку, решил покопаться. Низя использовать имена ID начинающиеся с цифр http://www.w3schools.com/css/css_selectors.asp , и не совсем понятно зачем так хитро создавать массив, Array(9), никакой разницы, на сколько я понял, между t = [] - нет.

**Comment by Kroid** [comment]
Привет, извини за задержку - не следил за этим репозиторием.

Обычно нет никакой практической разницы между способами инициализации массива, разве что по каким-то невообразимым причинам понадобится отслеживать длину этого массива. В моем случае это было что-то вроде самодокументирующегося кода (по крайней мере, я так думал в тот момент) - в крестиках-ноликах 9 полей, пусть массив отражает это.

Нельзя использовать id, начинающиеся с цифр, но в хроме это работало на тот момент (или какой у меня был браузер в 2013 году, уже не помню), а у меня было ограничение в 30 строк + не должно страдать форматирование и читаемость кода. Напиши неправильно или не пиши совсем. :)
